import {
  findPathToTarget,
  generateColorIndex,
  generateGameFieldState,
  generateNextColors,
  transformStateToMatrix,
  checkForScore,
  getStartGameFieldState,
  getStoredTopScore,
  getStoredScore,
  getStoredSoundSettings,
  getStoredAnimateSettings,
  saveToLocalStorage,
  getStartNextColorsSet,
  gameIsDone,
} from './gameUtils';
import {
  COLORS,
  DEFAULT_BALLS_COUNT,
  DEFAULT_FIELD_SIZE,
  SCORE_BY_LINE_LENGTH,
  STORAGE_GAME_STATE_KEY,
  MAX_SCORE_HEIGHT,
} from './constants';

export {
  findPathToTarget,
  generateColorIndex,
  generateGameFieldState,
  generateNextColors,
  transformStateToMatrix,
  checkForScore,
  getStartGameFieldState,
  getStoredScore,
  getStoredTopScore,
  getStoredSoundSettings,
  getStoredAnimateSettings,
  saveToLocalStorage,
  getStartNextColorsSet,
  gameIsDone,
  COLORS,
  DEFAULT_BALLS_COUNT,
  DEFAULT_FIELD_SIZE,
  SCORE_BY_LINE_LENGTH,
  STORAGE_GAME_STATE_KEY,
  MAX_SCORE_HEIGHT,
};
